// Discovery
const char* onvifHello = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:To>urn:schemas-xmlsoap-org:ws:2005:04/discovery</wsa:To>"
  "<wsa:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:Hello>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "<d:Types>dn:NetworkVideoTransmitter tds:Device</d:Types>"
  "<d:Scopes>"
  "onvif://www.onvif.org/location/%s "
  "onvif://www.onvif.org/name/%s "
  "onvif://www.onvif.org/hardware/%s "
  "onvif://www.onvif.org/type/audio_encoder "
  "onvif://www.onvif.org/type/video_encoder "
  "onvif://www.onvif.org/type/ptz"
  "onvif://www.onvif.org/Profile/Streaming"
  "onvif://www.onvif.org/Profile/T"
  "</d:Scopes>"
  "<d:XAddrs>http://%s/onvif/device_service</d:XAddrs>"
  "<d:MetadataVersion>1</d:MetadataVersion>"
  "</d:Hello>";

const char* onvifBye = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:To>urn:schemas-xmlsoap-org:ws:2005:04/discovery</wsa:To>"
  "<wsa:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Bye</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:Bye>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "</d:Bye>";

const char* onvifMatch = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:RelatesTo>uuid:%s</wsa:RelatesTo>"
  "<wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To>"
  "<wsa:Action>%s</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:%s>"
  "<d:%s>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "<d:Types>dn:NetworkVideoTransmitter tds:Device</d:Types>"
  "<d:Scopes>"
  "onvif://www.onvif.org/location/%s "
  "onvif://www.onvif.org/name/%s "
  "onvif://www.onvif.org/hardware/%s "
  "onvif://www.onvif.org/type/NetworkVideoTransmitter "
  "onvif://www.onvif.org/type/audio_encoder "
  "onvif://www.onvif.org/type/video_encoder "
  "onvif://www.onvif.org/type/ptz"
  "onvif://www.onvif.org/Profile/Streaming"
  "onvif://www.onvif.org/Profile/T"
  "</d:Scopes>"
  "<d:XAddrs>http://%s/onvif/device_service</d:XAddrs>"
  "<d:MetadataVersion>1</d:MetadataVersion>"
  "</d:%s>"
  "</d:%s>";