const char* getProfilesMedia2 = 
  "<s:Body>"
  "<tr2:GetProfilesResponse>"
  "<tr2:Profiles token=\"ProfileToken_1\" fixed=\"true\">"
  "<tr2:Name>ProfileName_1</tr2:Name>"
  "<tr2:Configurations>"

  "<tr2:VideoSourceConfiguration token=\"VideoSourceConfigurationToken_1\">"
  "<tr2:Name>VideoSourceConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>2</tr2:UseCount>"
  "<tr2:SourceToken>VideoSourceToken_1</tr2:SourceToken>"
  "<tr2:Bounds x=\"0\" y=\"0\" width=\"1280\" height=\"720\"/>"
  "</tr2:VideoSourceConfiguration>"

  "<tr2:AudioSourceConfiguration token=\"AudioSourceConfigurationToken_1\">"
  "<tr2:Name>AudioSourceConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>2</tr2:UseCount>"
  "<tr2:SourceToken>AudioSourceToken_1</tr2:SourceToken>"
  "</tr2:AudioSourceConfiguration>"

  "<tr2:VideoEncoderConfiguration token=\"VideoEncoderConfigurationToken_1\">"
  "<tr2:Name>VideoEncoderConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>1</tr2:UseCount>"
  "<tr2:Encoding>JPEG</tr2:Encoding>"
  "<tr2:Resolution>"
  "<tr2:Width>1280</tr2:Width>"
  "<tr2:Height>720</tr2:Height>"
  "</tr2:Resolution>"
  "<tr2:Quality>4</tr2:Quality>"
  "<tr2:RateControl>"
  "<tr2:FrameRateLimit>25</tr2:FrameRateLimit>"
  "<tr2:EncodingInterval>1</tr2:EncodingInterval>"
  "<tr2:BitrateLimit>2048</tr2:BitrateLimit>"
  "</tr2:RateControl>"
  "<tr2:SessionTimeout>PT10S</tr2:SessionTimeout>"
  "</tr2:VideoEncoderConfiguration>"

  "<tr2:AudioEncoderConfiguration token=\"AudioEncoderConfigurationToken_1\">"
  "<tr2:Name>AudioEncoderConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>2</tr2:UseCount>"
  "<tr2:Encoding>G726</tr2:Encoding>"
  "<tr2:Bitrate>32000</tr2:Bitrate>"
  "<tr2:SampleRate>16000</tr2:SampleRate>"
  "</tr2:AudioEncoderConfiguration>"

  "<tr2:AudioOutputConfiguration token=\"AudioOutputConfigurationToken_1\">"
  "<tr2:Name>AudioOutputConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>2</tr2:UseCount>"
  "<tr2:OutputToken>AudioOutputToken_1</tr2:OutputToken>"
  "<tr2:SendPrimacy>Primary</tr2:SendPrimacy>"
  "<tr2:OutputLevel>50</tr2:OutputLevel>"
  "</tr2:AudioOutputConfiguration>"

  "<tr2:PTZConfiguration token=\"PTZConfigurationToken_1\">"
  "<tr2:Name>PTZConfigurationName_1</tr2:Name>"
  "<tr2:UseCount>1</tr2:UseCount>"
  "<tr2:NodeToken>PTZNodeToken_1</tr2:NodeToken>"
  "<tr2:DefaultAbsolutePantTiltPositionSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tr2:DefaultAbsolutePantTiltPositionSpace>"
  "<tr2:DefaultAbsoluteZoomPositionSpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tr2:DefaultAbsoluteZoomPositionSpace>"
  "<tr2:DefaultRelativePanTiltTranslationSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tr2:DefaultRelativePanTiltTranslationSpace>"
  "<tr2:DefaultRelativeZoomTranslationSpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace</tr2:DefaultRelativeZoomTranslationSpace>"
  "<tr2:DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tr2:DefaultContinuousPanTiltVelocitySpace>"
  "<tr2:DefaultContinuousZoomVelocitySpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace</tr2:DefaultContinuousZoomVelocitySpace>"
  "<tr2:DefaultPTZTimeout>PT30S</tr2:DefaultPTZTimeout>"
  "<tr2:PanTiltLimits>"
  "<tr2:Range>"
  "<tr2:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tr2:URI>"
  "<tr2:XRange>"
  "<tr2:Min>-1.0</tr2:Min>"
  "<tr2:Max>1.0</tr2:Max>"
  "</tr2:XRange>"
  "<tr2:YRange>"
  "<tr2:Min>-1.0</tr2:Min>"
  "<tr2:Max>1.0</tr2:Max>"
  "</tr2:YRange>"
  "</tr2:Range>"
  "</tr2:PanTiltLimits>"
  "<tr2:ZoomLimits>"
  "<tr2:Range>"
  "<tr2:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tr2:URI>"
  "<tr2:XRange>"
  "<tr2:Min>0.0</tr2:Min>"
  "<tr2:Max>1.0</tr2:Max>"
  "</tr2:XRange>"
  "</tr2:Range>"
  "</tr2:ZoomLimits>"
  "</tr2:PTZConfiguration>"

  "</tr2:Configurations>"
  "</tr2:Profiles>"
  "</tr2:GetProfilesResponse>";

const char* getStreamUri2 = 
  "<s:Body>"
  "<tr2:GetStreamUriResponse>"
  "<tt:Uri>rtsp://%s:554</tt:Uri>"
  "</tr2:GetStreamUriResponse>";

const char* getSnapshotUri2 = 
  "<s:Body>"
  "<tr2:GetSnapshotUriResponse>"
  "<tt:Uri>http://%s/onvif/snapshot</tt:Uri>"
  "</tr2:GetSnapshotUriResponse>";
