// Media services

const char* getProfiles = // Used for both getProfile and getProfiles, since we only have 1 we can just reuse this
  "<s:Body>"
  "<trt:Get%sResponse>"
  "<trt:%s token=\"ProfileToken_1\" fixed=\"true\">"
  "<tt:Name>ProfileName_1</tt:Name>"
  
  "<tt:VideoSourceConfiguration token=\"VideoSourceConfigurationToken_1\">"
  "<tt:Name>VideoSourceConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:SourceToken>VideoSourceToken_1</tt:SourceToken>"
  "<tt:Bounds x=\"0\" y=\"0\" width=\"1280\" height=\"720\"/>"
  "</tt:VideoSourceConfiguration>"

  "<tt:AudioSourceConfiguration token=\"AudioSourceConfigurationToken_1\">"
  "<tt:Name>AudioSourceConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:SourceToken>AudioSourceToken_1</tt:SourceToken>"
  "</tt:AudioSourceConfiguration>"

  "<tt:VideoEncoderConfiguration token=\"VideoEncoderConfigurationToken_1\">"
  "<tt:Name>VideoEncoderConfigurationName_1</tt:Name>"
  "<tt:UseCount>1</tt:UseCount>"
  "<tt:Encoding>JPEG</tt:Encoding>"
  "<tt:Resolution>"
  "<tt:Width>1280</tt:Width>"
  "<tt:Height>720</tt:Height>"
  "</tt:Resolution>"
  "<tt:Quality>4</tt:Quality>"
  "<tt:RateControl>"
  "<tt:FrameRateLimit>25</tt:FrameRateLimit>"
  "<tt:EncodingInterval>1</tt:EncodingInterval>"
  "<tt:BitrateLimit>2048</tt:BitrateLimit>"
  "</tt:RateControl>"
  "<tt:SessionTimeout>PT10S</tt:SessionTimeout>"
  "</tt:VideoEncoderConfiguration>"

  "<tt:AudioEncoderConfiguration token=\"AudioEncoderConfigurationToken_1\">"
  "<tt:Name>AudioEncoderConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:Encoding>G726</tt:Encoding>"
  "<tt:Bitrate>32000</tt:Bitrate>"
  "<tt:SampleRate>16000</tt:SampleRate>"
  "</tt:AudioEncoderConfiguration>"

  "<tt:AudioOutputConfiguration token=\"AudioOutputConfigurationToken_1\">"
  "<tt:Name>AudioOutputConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:OutputToken>AudioOutputToken_1</tt:OutputToken>"
  "<tt:SendPrimacy>Primary</tt:SendPrimacy>"
  "<tt:OutputLevel>50</tt:OutputLevel>"
  "</tt:AudioOutputConfiguration>"

  "<tt:PTZConfiguration token=\"PTZConfigurationToken_1\">"
  "<tt:Name>PTZConfigurationName_1</tt:Name>"
  "<tt:UseCount>1</tt:UseCount>"
  "<tt:NodeToken>PTZNodeToken_1</tt:NodeToken>"
  "<tt:DefaultAbsolutePantTiltPositionSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:DefaultAbsolutePantTiltPositionSpace>"
  "<tt:DefaultAbsoluteZoomPositionSpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tt:DefaultAbsoluteZoomPositionSpace>"
  "<tt:DefaultRelativePanTiltTranslationSpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tt:DefaultRelativePanTiltTranslationSpace>"
  "<tt:DefaultRelativeZoomTranslationSpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace</tt:DefaultRelativeZoomTranslationSpace>"
  "<tt:DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tt:DefaultContinuousPanTiltVelocitySpace>"
  "<tt:DefaultContinuousZoomVelocitySpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace</tt:DefaultContinuousZoomVelocitySpace>"
  "<tt:DefaultPTZTimeout>PT30S</tt:DefaultPTZTimeout>"
  "<tt:PanTiltLimits>"
  "<tt:Range>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "<tt:YRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:YRange>"
  "</tt:Range>"
  "</tt:PanTiltLimits>"
  "<tt:ZoomLimits>"
  "<tt:Range>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>0.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "</tt:Range>"
  "</tt:ZoomLimits>"
  "</tt:PTZConfiguration>"

  "<tt:ImagingSettings token=\"ImagingSettingsToken_1\">"
  "<tt:BacklightCompensation>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>10.0</tt:Level>"
  "</tt:BacklightCompensation>"
  "<tt:Brightness>50.0</tt:Brightness>"
  "<tt:ColorSaturation>50.0</tt:ColorSaturation>"
  "<tt:Contrast>50.0</tt:Contrast>"
  "<tt:Exposure>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:Priority>LowNoise</tt:Priority>"
  "<tt:MinExposureTime>10.0</tt:MinExposureTime>"
  "<tt:MaxExposureTime>40000.0</tt:MaxExposureTime>"
  "<tt:MinGain>0.0</tt:MinGain>"
  "<tt:MaxGain>100.0</tt:MaxGain>"
  "</tt:Exposure>"
  "<tt:Sharpness>50.0</tt:Sharpness>"
  "<tt:WideDynamicRange>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>50.0</tt:Level>"
  "</tt:WideDynamicRange>"
  "<tt:WhiteBalance>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:CrGain>10.0</tt:CrGain>"
  "<tt:CbGain>10.0</tt:CbGain>"
  "</tt:WhiteBalance>"
  "</tt:ImagingSettings>"

  "</trt:%s>"
  "</trt:Get%sResponse>";

const char* getStreamUri = 
  "<s:Body>"
  "<trt:GetStreamUriResponse>"
  "<trt:MediaUri>"
  "<tt:Uri>rtsp://%s:554</tt:Uri>"
  "<tt:InvalidAfterConnect>false</tt:InvalidAfterConnect>"
  "<tt:InvalidAfterReboot>false</tt:InvalidAfterReboot>"
  "<tt:Timeout>PT0S</tt:Timeout>"
  "</trt:MediaUri>"
  "</trt:GetStreamUriResponse>";

const char* getSnapshotUri = 
  "<s:Body>"
  "<trt:GetSnapshotUriResponse>"
  "<trt:MediaUri>"
  "<tt:Uri>http://%s/onvif/snapshot</tt:Uri>"
  "<tt:InvalidAfterConnect>false</tt:InvalidAfterConnect>"
  "<tt:InvalidAfterReboot>false</tt:InvalidAfterReboot>"
  "<tt:Timeout>PT0S</tt:Timeout>"
  "</trt:MediaUri>"
  "</trt:GetSnapshotUriResponse>";

const char* getVideoSourceConfiguration = 
  "<s:Body>"
  "<trt:GetVideoSourceConfigurationResponse>"
  "<trt:Configurations token=\"VideoSourceConfigurationToken_1\">"
  "<tt:Name>VideoSourceConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:SourceToken>VideoSourceToken_1</tt:SourceToken>"
  "<tt:Bounds x=\"0\" y=\"0\" width=\"1280\" height=\"720\"/>"
  "</trt:Configurations>"
  "</trt:GetVideoSourceConfigurationResponse>";

const char* getVideoSources =
  "<s:Body>"
  "<trt:GetVideoSourcesResponse>"
  "<trt:VideoSources token=\"VideoSourceToken_1\">"
  "<tt:Framerate>25.0</tt:Framerate>"
  "<tt:Resolution>"
  "<tt:Width>1280</tt:Width>"
  "<tt:Height>720</tt:Height>"
  "</tt:Resolution>"
  "<tt:Imaging>"
  "<tt:BacklightCompensation>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>10.0</tt:Level>"
  "</tt:BacklightCompensation>"
  "<tt:Brightness>50.0</tt:Brightness>"
  "<tt:ColorSaturation>50.0</tt:ColorSaturation>"
  "<tt:Contrast>50.0</tt:Contrast>"
  "<tt:Exposure>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:Priority>LowNoise</tt:Priority>"
  "<tt:Window bottom=\"1.0\" top=\"0.0\" right=\"1.0\" left=\"0.0\"></tt:Window>"
  "<tt:MinExposureTime>10.0</tt:MinExposureTime>"
  "<tt:MaxExposureTime>40000.0</tt:MaxExposureTime>"
  "<tt:MinGain>0.0</tt:MinGain>"
  "<tt:MaxGain>100.0</tt:MaxGain>"
  "<tt:MinIris>0.0</tt:MinIris>"
  "<tt:MaxIris>10.0</tt:MaxIris>"
  "<tt:ExposureTime>4000.0</tt:ExposureTime>"
  "<tt:Gain>100.0</tt:Gain>"
  "<tt:Iris>10.0</tt:Iris>"
  "</tt:Exposure>"
  "<tt:Focus>"
  "<tt:AutoFocusMode>AUTO</tt:AutoFocusMode>"
  "<tt:DefaultSpeed>100.0</tt:DefaultSpeed>"
  "<tt:NearLimit>100.0</tt:NearLimit>"
  "<tt:FarLimit>1000.0</tt:FarLimit>"
  "</tt:Focus>"
  "<tt:IrCutFilter>AUTO</tt:IrCutFilter>"
  "<tt:Sharpness>50.0</tt:Sharpness>"
  "<tt:WideDynamicRange>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>50.0</tt:Level>"
  "</tt:WideDynamicRange>"
  "<tt:WhiteBalance>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:CrGain>10.0</tt:CrGain>"
  "<tt:CbGain>10.0</tt:CbGain>"
  "</tt:WhiteBalance>"
  "</tt:Imaging>"
  "</trt:VideoSources>"
  "</trt:GetVideoSourcesResponse>";

const char* getAudioDecoderConfigurations =
  "<s:Body>"
  "<trt:GetAudioDecoderConfigurationsResponse>"
  "<trt:Configurations>"
  "<tt:Name>AudioDecoderConfiguration_1</tt:Name>"
  "<tt:Token>audio_decoder_config_token</tt:Token>"
  "<tt:UseCount>1</tt:UseCount>"
  "</trt:Configurations>"
  "</trt:GetAudioDecoderConfigurationsResponse>";

const char* getVideoEncoderConfigurationOptions = 
  "<s:Body>"
  "<trt:GetVideoEncoderConfigurationOptionsResponse>"
  "<trt:Options>"
  "<tt:QualityRange>"
  "<tt:Min>0</tt:Min>"
  "<tt:Max>63</tt:Max>"
  "</tt:QualityRange>"
  "<tt:JPEG>"
  "%s" //ResolutionsAvailable
  "<tt:FrameRateRange>"
  "<tt:Min>1</tt:Min>"
  "<tt:Max>60</tt:Max>"
  "</tt:FrameRateRange>"
  "<tt:EncodingIntervalRange>"
  "<tt:Min>1</tt:Min>"
  "<tt:Max>5</tt:Max>"
  "</tt:EncodingIntervalRange>"
  "</tt:JPEG>"
  "</trt:Options>"
  "</trt:GetVideoEncoderConfigurationOptionsResponse>";

// Add Audio Output Configuration
const char* getAudioOutputConfiguration = 
  "<s:Body>"
  "<trt:GetAudioOutputConfigurationResponse>"
  "<trt:Configurations token=\"AudioOutputConfigurationToken_1\">"
  "<tt:Name>AudioOutputConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:OutputToken>AudioOutputToken_1</tt:OutputToken>"
  "<tt:SendPrimacy>Primary</tt:SendPrimacy>"
  "<tt:OutputLevel>50</tt:OutputLevel>"
  "</trt:Configurations>"
  "</trt:GetAudioOutputConfigurationResponse>";

// Add Audio Output Configuration Options
const char* getAudioOutputConfigurationOptions = 
  "<s:Body>"
  "<trt:GetAudioOutputConfigurationOptionsResponse>"
  "<trt:Options>"
  "<tt:OutputTokensAvailable>"
  "<tt:Token>AudioOutputToken_1</tt:Token>"
  "</tt:OutputTokensAvailable>"
  "<tt:SendPrimacyOptions>"
  "<tt:Option>Primary</tt:Option>"
  "<tt:Option>Secondary</tt:Option>"
  "</tt:SendPrimacyOptions>"
  "<tt:OutputLevelRange>"
  "<tt:Min>0</tt:Min>"
  "<tt:Max>100</tt:Max>"
  "</tt:OutputLevelRange>"
  "</trt:Options>"
  "</trt:GetAudioOutputConfigurationOptionsResponse>";

// Add Audio Output Configurations
const char* getAudioOutputConfigurations = 
  "<s:Body>"
  "<trt:GetAudioOutputConfigurationsResponse>"
  "<trt:Configurations token=\"AudioOutputConfigurationToken_1\">"
  "<tt:Name>AudioOutputConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:OutputToken>AudioOutputToken_1</tt:OutputToken>"
  "<tt:SendPrimacy>Primary</tt:SendPrimacy>"
  "<tt:OutputLevel>50</tt:OutputLevel>"
  "</trt:Configurations>"
  "</trt:GetAudioOutputConfigurationsResponse>";

const char* getAudioSources = 
  "<s:Body>"
  "<trt:GetAudioSourcesResponse>"
  "<trt:AudioSources token=\"AudioSourceToken_1\">"
  "<tt:Channels>1</tt:Channels>"
  "</trt:AudioSources>"
  "</trt:GetAudioSourcesResponse>";
