const char* getNodes = 
  "<s:Body>"
  "<tptz:GetNodesResponse>"
  "<tptz:PTZNode token=\"PTZNodeToken_1\">"
  "<tt:Name>PTZNodeName_1</tt:Name>"
  "<tt:SupportedPTZSpaces>"
  "<tt:AbsolutePanTiltPositionSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "<tt:YRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:YRange>"
  "</tt:AbsolutePanTiltPositionSpace>"
  "<tt:AbsoluteZoomPositionSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>0.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "</tt:AbsoluteZoomPositionSpace>"
  "</tt:SupportedPTZSpaces>"
  "<tt:MaximumNumberOfPresets>100</tt:MaximumNumberOfPresets>"
  "<tt:HomeSupported>true</tt:HomeSupported>"
  "</tptz:PTZNode>"
  "</tptz:GetNodesResponse>";

const char* getConfigurations = 
  "<s:Body>"
  "<tptz:GetConfigurationsResponse>"
  "<tptz:PTZConfiguration token=\"PTZConfigToken_1\">"
  "<tt:Name>PTZConfigName_1</tt:Name>"
  "<tt:UseCount>1</tt:UseCount>"
  "<tt:NodeToken>PTZNodeToken_1</tt:NodeToken>"
  "<tt:DefaultAbsolutePantTiltPositionSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI>"
  "</tt:DefaultAbsolutePantTiltPositionSpace>"
  "<tt:DefaultAbsoluteZoomPositionSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tt:URI>"
  "</tt:DefaultAbsoluteZoomPositionSpace>"
  "<tt:DefaultRelativePanTiltTranslationSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace</tt:URI>"
  "</tt:DefaultRelativePanTiltTranslationSpace>"
  "<tt:DefaultRelativeZoomTranslationSpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace</tt:URI>"
  "</tt:DefaultRelativeZoomTranslationSpace>"
  "<tt:DefaultContinuousPanTiltVelocitySpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</tt:URI>"
  "</tt:DefaultContinuousPanTiltVelocitySpace>"
  "<tt:DefaultContinuousZoomVelocitySpace>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace</tt:URI>"
  "</tt:DefaultContinuousZoomVelocitySpace>"
  "<tt:DefaultPTZSpeed>"
  "<tt:PanTilt x=\"1.0\" y=\"1.0\"/>"
  "<tt:Zoom x=\"1.0\"/>"
  "</tt:DefaultPTZSpeed>"
  "<tt:DefaultPTZTimeout>PT30S</tt:DefaultPTZTimeout>"
  "<tt:PanTiltLimits>"
  "<tt:Range>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "<tt:YRange>"
  "<tt:Min>-1.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:YRange>"
  "</tt:Range>"
  "</tt:PanTiltLimits>"
  "<tt:ZoomLimits>"
  "<tt:Range>"
  "<tt:URI>http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace</tt:URI>"
  "<tt:XRange>"
  "<tt:Min>0.0</tt:Min>"
  "<tt:Max>1.0</tt:Max>"
  "</tt:XRange>"
  "</tt:Range>"
  "</tt:ZoomLimits>"
  "</tptz:PTZConfiguration>"
  "</tptz:GetConfigurationsResponse>";

